@startuml Cabinet Medical


Title CabinetMedical

class Famille {
    -nom
    -nombreMembres
    -symptomesRecurrents
    +ajouterMembre()
    +supprimerMembre()
    +afficherMembres()
    +getNom()
    +setNom(String)
    +getNombreMembres()
    +setNombreMembre(int)
    +getSymptomesRecurrents()
    +setSymptomesRecurrents(symptomes: String)
}

class Appartenance {
    -patient
    -famille
    +ajouterAppartenance()
    +supprimerAppartenance()
    +afficherAppartenance()
    +getPatient()
    +getFamille()
}

class TraitementMedicamenteux {
    -medicament
    -traitement
    +ajouterTraitementMedicamenteux()
    +supprimerTraitementMedicamenteux()
    +afficherTraitementMedicamenteux()
}

class Agenda {
    -date
    -heure
    -medecin
    -patient
    -consultation
    +ajouterConsultation()
    +supprimerConsultation()
    +afficherConsultation()
    +getDate()
    +getHeure()
    +getMedecin()
    +getPatient()
    +getConsultation()
}

class Medicament {
    -reference
    -type
    -surOrdonance
    -datePeremption
    -prix
    -quantite
    -nom
    -marque
    -description
    -posologie
    -dureeTraitement
    +ajouterMedicament()
    +supprimerMedicament()
    +afficherMedicament()
    +getReference()
    +isSurOrdonnance()
    +getDatePeremption()
    +getPrix()
    +getQuantite()
    +getNom()
    +getMarque()
    +getDescription()
    +getPosologie()
    +getDureeTraitement()
}

class Traitement {
    -medecin
    -patient
    -reference
    -type
    -medicaments
    -posologie
    -duree
    -dateDebut
    -dateFin
    +ajouterTraitement()
    +supprimerTraitement()
    +afficherTraitement()
    +getMedecin()
    +getPatient()
    +getReference()
    +getType()
    +getMedicaments()
    +getPosologie()
    +getDuree()
    +getDateDebut()
    +getDateFin()
}

class Maladie {
    -reference
    -type
    +ajouterMaladie()
    +supprimerMaladie()
    +afficherMaladie()
    +getReference()
    +getType()
}

class Symptomes {
    -reference
    -type
    +ajouterSymptomes()
    +supprimerSymptomes()
    +afficherSymptomes()
}

class Consultation {
    -prix
    -reference
    -type
    -date
    -patient
    +ajouterConsultation()
    +supprimerConsultation()
    +afficherConsultation()
}

class CabinetMedical {
    -nom
    -adresse
    -telephone
    -listeMedecins
    -listePatients
    -listeConsultations
    +ajouterMedecin()
    +ajouterPatient()
    +ajouterVisite()
    +rechercherMedecin()
    +rechercherPatient()
    +rechercherVisite()
    +supprimerMedecin()
    +supprimerPatient()
    +supprimerVisite()
    +afficherMedecins()
    +afficherPatients()
    +afficherConsultations()
}

class Medecin {
    -specialite
    -numeroEmploye
    -nom
    -prenom
    -adresse
    -telephone
    -listePatients
    +ajouterPatient()
    +supprimerPatient()
    +afficherPatients()
    +prescrireMedicament()
    +effectuerConsultation()
}

class Patient {
    -nom
    -prenom
    -adresse
    -telephone
    -dateNaissance
    -sexe
    -numeroAssuranceMaladie
    -medecin
    +prendreRendezVous()
    +getMedecin()
}

left to right direction

Medecin "1.1" -- "0.*" Patient
CabinetMedical "1.1"  -- "0.*" Medecin
CabinetMedical "1.1"  -- "0.*" Patient
CabinetMedical "1.1"  -- "0.*" Consultation
Consultation "1.1" -- "0.*" Patient
Patient "0.*" -- "0.*" Symptomes
Patient "0.*" -- "0.*" Maladie
Patient "0.*" -- "0.*" Traitement
Symptomes "0.*" -- "0.*" Maladie
Maladie "1.*" -- "0.*" Traitement
Traitement "1.*" -- "0.*" Medicament
Agenda "1.1" -- "0.*" Consultation
Patient "1.*" -- "1.*" Famille
Famille "0.*" -- "0.*" Symptomes

@enduml