@startuml
start
:modérateur connecté;

:notification modération reçue;

:consultation du commentaire;

if(commentaire accepté ?) then (oui)
    :publication commentaire;
else (non)
    : commentaire masqué;
endif

stop
@enduml